steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY_NAME/app:$COMMIT_SHA', '.']

  # Push the image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-northeast1-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY_NAME/app:$COMMIT_SHA']

  # Deploy to GKE
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'container'
      - 'clusters'
      - 'get-credentials'
      - '$_CLUSTER_NAME'
      - '--zone=asia-northeast1'
      - '--project=$PROJECT_ID'

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: kubectl
    args:
      - 'set'
      - 'image'
      - 'deployment/$_DEPLOYMENT_NAME'
      - '$_DEPLOYMENT_NAME=asia-northeast1-docker.pkg.dev/$PROJECT_ID/$_REPOSITORY_NAME/app:$COMMIT_SHA'

timeout: '1800s'

substitutions:
  _CLUSTER_NAME: jjugccc-2025-spring
  _DEPLOYMENT_NAME: jjugccc-2025
  _REPOSITORY_NAME: gke-app-repository

options:
  machineType: 'E2_HIGHCPU_8'