version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT:-8080}:${PORT:-8080}"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/postgres
      - OPENFEATURE_PROVIDERS_FLAGD_HOST=flagd
    env_file:
      - .env
    depends_on:
      - db
      - flagd
    restart: unless-stopped

  db:
    image: postgres:16
    environment:
      - POSTGRES_USER=${SPRING_DATASOURCE_USERNAME}
      - POSTGRES_PASSWORD=${SPRING_DATASOURCE_PASSWORD}
      - POSTGRES_DB=postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    restart: unless-stopped

  flagd:
    image: ghcr.io/open-feature/flagd:latest
    container_name: flagd
    command: start --uri file:/flags.json --port 8013
    ports:
      - "8013:8013"
    volumes:
      - ./flags.json:/flags.json:ro
    restart: unless-stopped

volumes:
  postgres_data: 