version: '3.8'

services:
  postgres:
    image: postgres:16
    container_name: sample-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

  flagd:
    image: ghcr.io/open-feature/flagd:latest
    container_name: flagd
    command: start --uri file:/flags.json --port 8013
    ports:
      - "8013:8013"
    volumes:
      - ./flags.json:/flags.json:ro
    restart: unless-stopped

volumes:
  pgdata: 