apiVersion: apps/v1
kind: Deployment
metadata:
  name: jjugccc-2025
  labels:
    app: jjugccc-2025
spec:
  replicas: 1
  selector:
    matchLabels:
      app: jjugccc-2025
  template:
    metadata:
      labels:
        app: jjugccc-2025
    spec:
      containers:
      - name: jjugccc-2025
        image: nginx:latest
        ports:
        - containerPort: 8080
        resources:
          requests:
            cpu: "250m"
            memory: "512Mi"
          limits:
            cpu: "500m"
            memory: "1Gi"
        env:
        - name: SPRING_PROFILES_ACTIVE
          value: "prod"
        - name: SPRING_DATASOURCE_URL
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: url
        - name: SPRING_DATASOURCE_USERNAME
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: username
        - name: SPRING_DATASOURCE_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-credentials
              key: password
---
apiVersion: v1
kind: Service
metadata:
  name: jjugccc-2025
  annotations:
    cloud.google.com/neg: '{"ingress": true}'
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 8080
    protocol: TCP
  selector:
    app: jjugccc-2025 